"""Multi-regime detector validation — does a cell's edge PERSIST across regimes?

Implements ``docs/superpowers/specs/2026-08-12-multi-regime-validation-design.md``.
Phase 1 selects the pre-registered cells on **pooled** ``avg_r`` only — never the
split — which is what keeps selection orthogonal to the contrast being tested.
Phase 2 computes the paired regime difference and reports a verdict.

Promoted out of ``docs/plans/scratch/`` on 2026-08-14. Two defects came with it,
both invisible while the file was untracked:

**1. The verdict criterion was not a power test.** The original declared a
*powered null* from ``|Δ| < MDE`` on a hardcoded ``tf in ("15m", "1h")``
whitelist. Since ``MDE = 2.802 × SE``, that reduces to ``|t| < 2.802`` — a
significance test wearing a power label, computed entirely from the data's own
noise and therefore incapable of ruling an effect *out*. It is the sixth member
of the family fixed at five other sites by ST26/ST27, and it looks different
again from all five: not a sample-size floor, not failure-to-clear-a-threshold.
Verdicts now come from :func:`analytics.audit_guard.powered_null` — CI
containment inside ``±bar`` — and the MDE is printed as a scale stamp only.

Re-scored on the filed 2026-08-12 table, **0 of 3 filed powered nulls survive**
(CI half-widths 2.1× / 3.8× / 7.1× the bar). No verdict direction reverses: no
cell was significant then and none is now, so the study's NO stands and only the
strength of the claim changes, from *ruled out* to *not ruled out*.

**2. It could silently answer nothing.** Both legs were generated by re-running
backtests over 2021/2022, and ``/db-update`` has since overwritten
``backtest_trades`` back to 2025-09-12 onward — so a re-run now finds 0 rows in
both windows. The original printed ``eligible: 0`` and exited 0, which reads as
"no cells qualified" rather than "the population is gone". :func:`load_legs`
raises instead. **Regenerate the legs before running** — this tool queries them,
it does not create them.

Usage::

    PYTHONPATH=. poetry run python tools/multi_regime_study.py
    PYTHONPATH=. poetry run python tools/multi_regime_study.py --bar 0.05
"""

from __future__ import annotations

import argparse
import math
import statistics
from dataclasses import dataclass
from datetime import UTC, datetime
from statistics import NormalDist

import duckdb

from analytics.audit_guard import DEFAULT_BAR, powered_null
from analytics.store import DEFAULT_DB_PATH, load_backtest_trades

NORM = NormalDist()
Z95 = NORM.inv_cdf(0.975)  # 1.9600, the CI the verdict rests on
Z80 = NORM.inv_cdf(0.80)  # 0.8416, the 80%-power MDE stamp
N_CELLS = 4
MIN_N_PER_LEG = 30
DISP_FLOOR = 0.05  # spec §Construction step 6

# spec §5 — max of the two legs' deflators for that grain, conservative. These
# are the 25-symbol panel's 2.92x RECOMPUTED for the panels this study actually
# runs; reusing a filed deflator across panels is the H15 portable-number trap.
# Regenerate with tools/multi_regime_deflator.py, never by hand.
DEFLATOR = {"15m": 1.628, "1h": 3.331, "4h": 3.331, "1d": 3.331}

BULL = ("bull_2021", 2021)
BEAR = ("bear_2022", 2022)

VERDICT_DETECTED = "REGIME DEPENDENCE DETECTED"
VERDICT_POWERED_NULL = "POWERED NULL"
VERDICT_INSUFFICIENT = "INSUFFICIENT"


def ms(year: int) -> int:
    """UTC epoch-ms for Jan 1 of ``year``.

    Bounds are computed in Python, never in SQL: DuckDB's session TimeZone is
    ``Asia/Kuala_Lumpur`` here, so a ``date_trunc`` boundary would land 8h off.
    """
    return int(datetime(year, 1, 1, tzinfo=UTC).timestamp() * 1000)


@dataclass(frozen=True)
class CellResult:
    """One pre-registered cell's paired regime difference and its verdict.

    ``mde`` is reported for scale only. It is a function of ``se`` alone, so it
    can say how large an effect would have been visible — never whether a small
    one was ruled out. That distinction is the defect this module was promoted
    to fix; ``verdict`` comes from ``ci_lo``/``ci_hi`` against ``bar``.
    """

    label: str
    tf: str
    delta: float
    se: float
    t_stat: float
    mde: float
    ci_lo: float
    ci_hi: float
    n_bull: int
    n_bear: int
    deflator: float
    verdict: str
    reason: str


def load_legs(
    conn: duckdb.DuckDBPyConnection,
) -> dict[tuple[str, str, str], dict[str, list[float]]]:
    """Deduplicated per-trade R for every cell, split into the two regime legs.

    Dedup on ``(symbol, timeframe, strategy, direction, entry_time)`` is
    mandatory, not hygiene: repeated backtest runs leave ``backtest_trades``
    with a ~5.29× duplication factor, which inflates every ``n`` ~5× and every
    ``t`` ~2.3×.

    Raises ``RuntimeError`` when either leg is empty. The legs are generated by
    re-running backtests over 2021/2022 and are routinely overwritten by
    ``/db-update``; an empty result is a missing population, not a finding, and
    the untracked original reported the two identically.
    """
    pool = load_backtest_trades(
        conn,
        columns=("strategy", "timeframe", "direction", "entry_time", "pnl_r"),
    )
    cells: dict[tuple[str, str, str], dict[str, list[float]]] = {}
    for strat, tf, direction, entry_time, r in pool.itertuples(index=False, name=None):
        if ms(BULL[1]) <= entry_time < ms(BULL[1] + 1):
            leg = "bull"
        elif ms(BEAR[1]) <= entry_time < ms(BEAR[1] + 1):
            leg = "bear"
        else:
            continue
        cells.setdefault((strat, tf, direction), {"bull": [], "bear": []})[leg].append(
            float(r)
        )

    n_bull = sum(len(v["bull"]) for v in cells.values())
    n_bear = sum(len(v["bear"]) for v in cells.values())
    if n_bull == 0 or n_bear == 0:
        span = (
            (pool["entry_time"].min(), pool["entry_time"].max())
            if not pool.empty
            else None
        )
        lo = (
            datetime.fromtimestamp(span[0] / 1000, UTC).date()
            if span and span[0]
            else "?"
        )
        hi = (
            datetime.fromtimestamp(span[1] / 1000, UTC).date()
            if span and span[1]
            else "?"
        )
        raise RuntimeError(
            f"backtest_trades has no rows in the {BULL[0]} leg ({n_bull}) or the "
            f"{BEAR[0]} leg ({n_bear}); the table spans {lo} -> {hi}. Both legs are "
            "GENERATED by re-running backtests over those years and are overwritten "
            "by /db-update. Regenerate them before running this study — an empty "
            "population is not a null result."
        )
    return cells


def select_cells(
    cells: dict[tuple[str, str, str], dict[str, list[float]]],
    *,
    n_cells: int = N_CELLS,
    min_n_per_leg: int = MIN_N_PER_LEG,
    disp_floor: float = DISP_FLOOR,
) -> tuple[list[tuple[tuple[str, str, str], float, int, int]], int, int]:
    """Phase 1 — rank eligible cells by POOLED ``avg_r``, blind to the split.

    Returns ``(eligible_sorted, dropped_on_n, dropped_on_dispersion)``. The
    dispersion floor excludes cells whose per-leg R is effectively constant: one
    such cell (``bos/1d/long``, 36 trades all ≈ −1.0076R, sd 0.0022) carries a
    per-trade Sharpe of −461 and inflates a trial-family variance 50,000×.
    """
    eligible: list[tuple[tuple[str, str, str], float, int, int]] = []
    dropped_n = dropped_disp = 0
    for key, legs in cells.items():
        bull, bear = legs["bull"], legs["bear"]
        if len(bull) < min_n_per_leg or len(bear) < min_n_per_leg:
            dropped_n += 1
            continue
        if statistics.stdev(bull) < disp_floor or statistics.stdev(bear) < disp_floor:
            dropped_disp += 1
            continue
        eligible.append((key, statistics.fmean(bull + bear), len(bull), len(bear)))
    eligible.sort(key=lambda x: -x[1])
    return eligible, dropped_n, dropped_disp


def score_cell(
    key: tuple[str, str, str],
    legs: dict[str, list[float]],
    *,
    bar: float,
) -> CellResult:
    """Phase 2 — paired regime difference for one cell, with its verdict.

    The verdict is CI containment against ``bar`` via
    :func:`analytics.audit_guard.powered_null`, **not** ``|Δ| < MDE``. A cell
    that is neither significant nor contained is ``INSUFFICIENT``: it failed to
    detect an effect and failed to rule one out, which are the same outcome only
    if you never look at the interval.
    """
    strategy, tf, direction = key
    bull, bear = legs["bull"], legs["bear"]
    mean_bull, mean_bear = statistics.fmean(bull), statistics.fmean(bear)
    delta = mean_bull - mean_bear
    sd_pooled = statistics.stdev(bull + bear)
    se_naive = sd_pooled * math.sqrt(1.0 / len(bull) + 1.0 / len(bear))
    deflator = DEFLATOR[tf]
    se = se_naive * deflator
    t_stat = delta / se
    ci_lo, ci_hi = delta - Z95 * se, delta + Z95 * se

    if abs(t_stat) >= Z95:
        verdict = VERDICT_DETECTED
        reason = f"{'BULL > bear' if delta > 0 else 'BEAR > bull'}; nominal, before multiplicity"
    elif powered_null(ci_lo, ci_hi, bar=bar):
        verdict = VERDICT_POWERED_NULL
        reason = f"CI [{ci_lo:+.4f}, {ci_hi:+.4f}] lies inside ±{bar:.2f}R"
    else:
        verdict = VERDICT_INSUFFICIENT
        reason = (
            f"CI [{ci_lo:+.4f}, {ci_hi:+.4f}] does not clear ±{bar:.2f}R "
            f"(half-width {Z95 * se / bar:.1f}x the bar)"
        )

    return CellResult(
        label=f"{strategy}/{tf}/{direction}",
        tf=tf,
        delta=delta,
        se=se,
        t_stat=t_stat,
        mde=(Z95 + Z80) * se,
        ci_lo=ci_lo,
        ci_hi=ci_hi,
        n_bull=len(bull),
        n_bear=len(bear),
        deflator=deflator,
        verdict=verdict,
        reason=reason,
    )


def bonferroni_threshold(n_tests: int) -> float:
    """Two-sided |t| a cell must reach at Bonferroni-corrected alpha.

    Pre-registering four cells and testing each at 95% carries a ~19% chance of
    one false positive. The spec omitted the correction and the study returned
    exactly one nominal hit; the amendment log records the fix.
    """
    return float(NORM.inv_cdf(1.0 - 0.05 / (2.0 * max(n_tests, 1))))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", default=str(DEFAULT_DB_PATH), help="analytics DB path")
    parser.add_argument(
        "--bar",
        type=float,
        default=DEFAULT_BAR,
        help=f"effect-size floor in per-trade R (default {DEFAULT_BAR}, ~2.5x round-trip cost)",
    )
    args = parser.parse_args()

    conn = duckdb.connect(args.db, read_only=True)
    cells = load_legs(conn)
    eligible, dropped_n, dropped_disp = select_cells(cells)
    selected = eligible[:N_CELLS]

    print(f"candidate cells: {len(cells)}")
    print(
        f"eligible (n>={MIN_N_PER_LEG}/leg): {len(eligible)}"
        f"   dropped: {dropped_n} on n, {dropped_disp} on dispersion"
    )

    print("\n" + "=" * 74)
    print("PHASE 1 — PRE-REGISTERED CELLS (selected on POOLED avg_r, blind to leg)")
    print("=" * 74)
    print(
        f"{'#':>2}  {'strategy':<24}{'tf':>5}{'dir':>7}{'pooled avg_r':>14}{'n_bull':>8}{'n_bear':>8}"
    )
    for i, (key, mu, n_b, n_r) in enumerate(selected, 1):
        print(
            f"{i:>2}  {key[0]:<24}{key[1]:>5}{key[2]:>7}{mu:>+14.4f}{n_b:>8,}{n_r:>8,}"
        )

    print("\n" + "=" * 74)
    print(f"PHASE 2 — PAIRED REGIME DIFFERENCE (bull − bear), bar = ±{args.bar:.2f}R")
    print("=" * 74)
    print(f"{'cell':<34}{'delta':>9}{'CI_lo':>9}{'CI_hi':>9}{'t':>7}{'MDE*':>8}")
    results = [score_cell(key, cells[key], bar=args.bar) for key, _, _, _ in selected]
    for r in results:
        print(
            f"{r.label:<34}{r.delta:>+9.4f}{r.ci_lo:>+9.4f}{r.ci_hi:>+9.4f}"
            f"{r.t_stat:>7.2f}{r.mde:>+8.3f}"
        )
    print("\n* MDE is a SCALE STAMP, not a criterion — it is a function of SE alone.")

    threshold = bonferroni_threshold(len(results))
    print("\n" + "=" * 74)
    print(
        f"VERDICT   (Bonferroni over {len(results)} pre-registered tests: |t| >= {threshold:.3f})"
    )
    print("=" * 74)
    for r in results:
        survives = abs(r.t_stat) >= threshold
        print(f"  {r.label}")
        print(
            f"    delta={r.delta:+.4f}R  t={r.t_stat:+.2f} (deflator x{r.deflator})"
            f"  n={r.n_bull:,}/{r.n_bear:,}"
        )
        print(f"    -> {r.verdict} — {r.reason}")
        if r.verdict == VERDICT_DETECTED and not survives:
            print(
                f"       NOT significant after multiplicity (|t| {abs(r.t_stat):.2f} < {threshold:.3f})"
            )


if __name__ == "__main__":
    main()
