name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (requirements.txt)
        if: exists('requirements.txt')
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install dependencies (Poetry)
        if: exists('pyproject.toml')
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run tests with pytest
        run: |
          if [ -f pyproject.toml ]; then
            poetry run pytest
          else
            pytest
          fi 