name: Telegram Monitor

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:      # allow manual trigger

jobs:
  run-monitors:
    runs-on: ubuntu-latest

    env:
      BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
      BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run price_monitor
        run: python monitor/price_monitor.py --once --telegram

      - name: Run position_monitor
        run: python monitor/position_monitor.py --telegram
